name: Build and Push Docker Image

on:
  push:
    branches:
      - master  # Change this to the branch you want to trigger on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - name: Log in to Docker Hub
        run: docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}" 

      - name: Build the Docker image
        run: docker build -t ${{ secrets.DOCKER_REPOSITORY }}:latest .

      - name: Push the Docker image
        run: docker push ${{ secrets.DOCKER_REPOSITORY }}:latest

